
services:
  web:
    build: .
    command: ["sh", "docker-entrypoint.sh"]
    ports:
      - 8000:8000
    environment:
      - PAGINATION_DEFAULT_CLASS=rest_framework.pagination.LimitOffsetPagination
      - PAGINATION_PAGE_SIZE=10
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - .:/app     
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
  celery:
    build: .
    command: celery -A new_app_searcher worker --loglevel=info
    environment:
      - PAGINATION_DEFAULT_CLASS=rest_framework.pagination.LimitOffsetPagination
      - PAGINATION_PAGE_SIZE=10
    depends_on:
      - redis
    volumes:
      - .:/app
  celery-beat:
    build: .
    command: celery -A new_app_searcher beat --loglevel=info
    environment:
      - PAGINATION_DEFAULT_CLASS=rest_framework.pagination.LimitOffsetPagination
      - PAGINATION_PAGE_SIZE=10
    depends_on:
      - redis
    volumes:
      - .:/app
volumes:
  redisdata:  
