# Generated by Django 3.2.12 on 2022-03-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='link',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
