# Generated by Django 3.2.12 on 2022-03-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20220318_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='author_last_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='maintainer_first_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='maintainer_last_name',
        ),
        migrations.AddField(
            model_name='package',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='maintainer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
